name = "barbaar"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

build = { command = "npm run build", cwd = "./", watch_paths = ["src/**/*.tsx", "src/**/*.ts"] }
main = "server.ts"

[env.production]
name = "barbaar-prod"
route = "barbaarapp.com/*"
zone_id = ""

[build.upload]
format = "modules"
main = "./dist/server.js"

[docs]
# https://developers.cloudflare.com/workers/platform/triggers/crons/
crons = []
