export const colors = {
  ivory: '#f0ece1',
  paper: '#ffffff',
  ink: '#1d2823',
  inkSoft: '#4d5d54',
  indigo: '#384c43',
  indigoDeep: '#2f3f37',
  indigoSoft: '#e4eae6',
  amber: '#c07a34',
  amberSoft: '#f8efe0',
  acacia: '#64a461',
  acaciaSoft: '#eff5ef',
  clay: '#b56254',
  claySoft: '#fbf2f0',
  line: '#dfdad0',
  danger: '#b93c3c',
  bgDark: '#111827',
  cardDark: '#1f2937',
};

export const DEFAULT_THERAPISTS = [
  {
    id: 't1',
    name: 'Dr. Amina Hassan',
    credentials: 'PhD, Clinical Psychologist',
    category: 'cbt',
    gender: 'female',
    languages: ['Somali', 'English'],
    experience: 9,
    rating: 4.9,
    reviews: 127,
    price: 60,
    priceUnit: 'session',
    sessionsIncluded: null,
    shortBio: 'Helps clients quiet anxious and intrusive thoughts using evidence-based CBT, in a space that respects culture and faith.',
    longBio: "Dr. Hassan has spent nine years helping Somali clients work through anxiety, depression, and OCD using cognitive behavioral therapy. She was trained in Nairobi and London, and tailors CBT to fit each client's life, culture, and beliefs rather than the other way around.",
    specialties: ['Anxiety', 'Depression', 'OCD', 'CBT'],
    initials: 'AH',
    color: '#64a461',
    availability: {
      days: ['Mon', 'Tue', 'Wed', 'Thu'],
      slots: ['9:00 AM', '11:00 AM', '2:00 PM', '4:00 PM'],
    },
    active: true,
    email: 'amina.hassan@barbaar.com',
  },
  {
    id: 't2',
    name: 'Abdirahman Jama',
    credentials: 'LMFT, Licensed Therapist',
    category: 'cbt',
    gender: 'male',
    languages: ['Somali', 'English'],
    experience: 6,
    rating: 4.7,
    reviews: 64,
    price: 50,
    priceUnit: 'session',
    sessionsIncluded: null,
    shortBio: "Works with Somali men carrying anxiety and pressure to 'hold it together' — practical tools, no judgment.",
    longBio: "Abdirahman focuses on anxiety, low mood, and stress, especially for men who were never taught it's okay to ask for help. His sessions are direct, practical, and grounded in CBT techniques you can use the same day.",
    specialties: ['Anxiety', 'Depression', 'Stress', 'CBT'],
    initials: 'AJ',
    color: '#64a461',
    availability: {
      days: ['Tue', 'Wed', 'Fri', 'Sat'],
      slots: ['10:00 AM', '1:00 PM', '3:00 PM', '6:00 PM'],
    },
    active: true,
    email: 'abdirahman.jama@barbaar.com',
  },
  {
    id: 't3',
    name: 'Dr. Yusuf Warsame',
    credentials: 'PsyD, Couples Therapist',
    category: 'couples',
    gender: 'male',
    languages: ['Somali', 'English', 'Arabic'],
    experience: 11,
    rating: 4.9,
    reviews: 98,
    price: 75,
    priceUnit: 'session',
    sessionsIncluded: null,
    shortBio: 'Guides couples through distance, trust, and communication — grounded in respect for Somali family values.',
    longBio: 'Dr. Warsame has worked with over 300 couples on communication, trust, and conflict. He understands the weight of family and community expectations, and helps partners rebuild connection without losing their values.',
    specialties: ['Communication', 'Trust', 'Pre-marital', 'Conflict'],
    initials: 'YW',
    color: '#b56254',
    availability: {
      days: ['Mon', 'Wed', 'Thu', 'Sat'],
      slots: ['9:00 AM', '12:00 PM', '3:00 PM', '5:00 PM'],
    },
    active: true,
    email: 'yusuf.warsame@barbaar.com',
  },
  {
    id: 't4',
    name: 'Sagal Nur',
    credentials: 'LCSW, Relationship Therapist',
    category: 'couples',
    gender: 'female',
    languages: ['Somali', 'English'],
    experience: 7,
    rating: 4.8,
    reviews: 71,
    price: 65,
    priceUnit: 'session',
    sessionsIncluded: null,
    shortBio: 'Helps partners rebuild connection after conflict, distance, or big transitions like migration and marriage.',
    longBio: 'Sagal specializes in helping couples navigate life transitions — new marriages, migration, blended families — with a calm, structured approach that keeps both partners feeling heard.',
    specialties: ['Connection', 'Conflict Repair', 'Life Transitions'],
    initials: 'SN',
    color: '#b56254',
    availability: {
      days: ['Sun', 'Tue', 'Thu', 'Fri'],
      slots: ['11:00 AM', '1:00 PM', '4:00 PM', '6:00 PM'],
    },
    active: true,
    email: 'sagal.nur@barbaar.com',
  },
  {
    id: 't5',
    name: 'Dr. Ifrah Abdi',
    credentials: 'PhD, Transformation Coach & Psychologist',
    category: 'premium',
    gender: 'female',
    languages: ['Somali', 'English'],
    experience: 13,
    rating: 5.0,
    reviews: 52,
    price: 320,
    priceUnit: 'program',
    sessionsIncluded: 6,
    shortBio: 'Leads a focused 6-week program for people ready to break real patterns — not just cope, but change.',
    longBio: "Dr. Abdi's 6-week transformation program is built for people who feel stuck in the same patterns despite years of 'coping'. Sessions are longer, homework is real, and the goal is measurable change, not just relief.",
    specialties: ['Life Transitions', 'Identity', 'Deep Change', 'Goal-focused'],
    initials: 'IA',
    color: '#c07a34',
    availability: {
      days: ['Mon', 'Tue', 'Thu'],
      slots: ['10:00 AM', '1:00 PM', '4:00 PM'],
    },
    active: true,
    email: 'ifrah.abdi@barbaar.com',
  },
  {
    id: 't6',
    name: 'Mohamed Ali Farah',
    credentials: 'PsyD, Clinical Psychologist',
    category: 'premium',
    gender: 'male',
    languages: ['Somali', 'English'],
    experience: 15,
    rating: 4.9,
    reviews: 83,
    price: 280,
    priceUnit: 'program',
    sessionsIncluded: 6,
    shortBio: "A 6-week intensive for people ready to face what's been on hold — career, identity, relationships.",
    longBio: 'Mohamed built his 6-week intensive for high performers who look fine from the outside but feel stuck inside. Expect direct feedback, structured milestones, and a program that ends with a plan, not just a feeling.',
    specialties: ['High-performers', 'Purpose', 'Deep Change'],
    initials: 'MF',
    color: '#c07a34',
    availability: {
      days: ['Wed', 'Thu', 'Fri', 'Sat'],
      slots: ['9:00 AM', '12:00 PM', '3:00 PM'],
    },
    active: true,
    email: 'mohamed.farah@barbaar.com',
  },
];
